spring:
  application:
  name=product-catalogue

# PostgreSQL Database
datasource:\
  url:jdbc:postgresql://localhost:5432/productdb
  username:postgres
  password:postgres123

# Hibernate
jpa:\
  hibernate:\
  ddl-auto=update
  show-sql=true
  properties:\
  hibernate:\
  format_sql:true

# PostgreSQL Dialect
database-platform:org.hibernate.dialect.PostgreSQLDialect

# Server
server:\
  port:8080
