apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: product-catalogue-db
  namespace: production

spec:
  provider: aws

  parameters:
    region: ap-south-1
    usePodIdentity: "true"

    objects: |
      - objectName: "arn:aws:secretsmanager:ap-south-1:379063509266:secret:rds!db-e0d6c1a7-5fca-4659-97bd-247d8d42f68d-VJBnFf"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password

  secretObjects:
    - secretName: product-catalogue-db
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password